name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

  preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy to Vercel (Preview)
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --confirm --build-env VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}

      - name: Add preview link to PR
        run: |
          PREVIEW_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --confirm)
          echo "🚀 Preview URL: $PREVIEW_URL"
          gh pr comment ${{ github.event.pull_request.number }} --body "🚀 **Preview URL:** $PREVIEW_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
